version: "3"
services:
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    ports:
#      - '2181:2181'
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#  kafka:
#    image: 'bitnami/kafka:latest'
#    ports:
#      - '9092:9092'
#    environment:
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
#  jetstream-nats:
#    image: synadia/jsm:latest
#    entrypoint: /nats-server
#    ports:
#      - 4222:4222
  kafka:
    image: landoop/fast-data-dev
    environment:
      - ADV_HOST=127.0.0.1
      - BROWSECONFIGS=1
    volumes:
      - ~/localstack/landoop/data/:/data/
    ports:
      - "2181:2181"
      - "3030:3030"
#      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    networks:
      - localstack

  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    networks:
      - localstack

networks:
  localstack:
    driver: bridge