micronaut:
  application:
    name: employeePub
  server:
    port: 8080
    cors:
      enabled: true
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    endpoints:
      all:
        enabled: true
        sensitive: false
      health:
        enabled: true
      beans:
        enabled: true
      info:
        enabled: true
      routes:
        enabled: true
---
#nats.addresses: nats://localhost:4222
kafka.bootstrap.servers: localhost:9092
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
